//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Item_Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Measurement_Id { get; set; }
        public Nullable<int> SalesAccountId { get; set; }
        public Nullable<int> InventoryAccountId { get; set; }
        public Nullable<int> CostOfGoodsSoldAccountId { get; set; }
        public Nullable<int> InventoryAdjustmentAccountId { get; set; }
        public string Bar_Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Unit_Cost { get; set; }
        public Nullable<decimal> Sale_Price { get; set; }
        public Nullable<int> Re_Order_Leval { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> Business_Division_Id { get; set; }
        public string ReferenceNo { get; set; }
        public string Description { get; set; }
    }
}
