//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SameSoftwareWebEntities : DbContext
    {
        public SameSoftwareWebEntities()
            : base("name=SameSoftwareWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IssueType> IssueTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblApplication> tblApplications { get; set; }
        public virtual DbSet<tblAppVersion> tblAppVersions { get; set; }
        public virtual DbSet<tblCashFlow> tblCashFlows { get; set; }
        public virtual DbSet<tblCustomerTranactionType> tblCustomerTranactionTypes { get; set; }
        public virtual DbSet<TblCustomerTransaction> TblCustomerTransactions { get; set; }
        public virtual DbSet<tblCustomerType> tblCustomerTypes { get; set; }
        public virtual DbSet<tblFeatureRequest> tblFeatureRequests { get; set; }
        public virtual DbSet<tblPayment_Voucher> tblPayment_Voucher { get; set; }
        public virtual DbSet<tblProblem> tblProblems { get; set; }
        public virtual DbSet<tblProject> tblProjects { get; set; }
        public virtual DbSet<tblReceipt_Voucher> tblReceipt_Voucher { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblConnection_Data> tblConnection_Data { get; set; }
        public virtual DbSet<tblWebLog> tblWebLogs { get; set; }
        public virtual DbSet<tblExpenseType> tblExpenseTypes { get; set; }
        public virtual DbSet<tblCash_Flow> tblCash_Flow { get; set; }
        public virtual DbSet<tblChart_Of_Account_Assignment> tblChart_Of_Account_Assignment { get; set; }
        public virtual DbSet<tblChart_Of_Accounts> tblChart_Of_Accounts { get; set; }
        public virtual DbSet<tblJournal> tblJournals { get; set; }
        public virtual DbSet<tblJournal_Details> tblJournal_Details { get; set; }
        public virtual DbSet<tblSMS_API_DATA> tblSMS_API_DATA { get; set; }
        public virtual DbSet<TblLog> TblLogs { get; set; }
        public virtual DbSet<tblVendor_Invoice> tblVendor_Invoice { get; set; }
        public virtual DbSet<tblVendor_Tran_Type> tblVendor_Tran_Type { get; set; }
        public virtual DbSet<tblVendor_Transaction> tblVendor_Transaction { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Inventory_Types> Inventory_Types { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Measurement> Measurements { get; set; }
        public virtual DbSet<Quotation_Details> Quotation_Details { get; set; }
        public virtual DbSet<tblCompanyInfo> tblCompanyInfoes { get; set; }
        public virtual DbSet<tblPurchase_Order> tblPurchase_Order { get; set; }
        public virtual DbSet<tblPurchase_Order_Details> tblPurchase_Order_Details { get; set; }
        public virtual DbSet<tblQuotation> tblQuotations { get; set; }
        public virtual DbSet<tblSetting2> tblSetting2 { get; set; }
        public virtual DbSet<tblVendor_Documents> tblVendor_Documents { get; set; }
        public virtual DbSet<VendorInstallmentPlan> VendorInstallmentPlans { get; set; }
        public virtual DbSet<tblInventory_Transaction_Details> tblInventory_Transaction_Details { get; set; }
        public virtual DbSet<tblInventory_Transactions> tblInventory_Transactions { get; set; }
        public virtual DbSet<tblBatch> tblBatches { get; set; }
        public virtual DbSet<Business_Division> Business_Division { get; set; }
        public virtual DbSet<tblVendor> tblVendors { get; set; }
        public virtual DbSet<tblSetting> tblSettings { get; set; }
        public virtual DbSet<tblCustomer_Transaction> tblCustomer_Transaction { get; set; }
        public virtual DbSet<tblCustomerInvoiceGroup> tblCustomerInvoiceGroups { get; set; }
        public virtual DbSet<tblInvoiceGroupDetail> tblInvoiceGroupDetails { get; set; }
        public virtual DbSet<tblCustomer_Tran_Type> tblCustomer_Tran_Type { get; set; }
        public virtual DbSet<tblPaymentMethod> tblPaymentMethods { get; set; }
        public virtual DbSet<InstallmentPlan> InstallmentPlans { get; set; }
        public virtual DbSet<tblInvoice> tblInvoices { get; set; }
        public virtual DbSet<tblCustomer_Transaction_Detail> tblCustomer_Transaction_Detail { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<TblDocument> TblDocuments { get; set; }
        public virtual DbSet<tblExpense> tblExpenses { get; set; }
        public virtual DbSet<CustomerTask> CustomerTasks { get; set; }
        public virtual DbSet<tblTask> tblTasks { get; set; }
        public virtual DbSet<tblMonth> tblMonths { get; set; }
        public virtual DbSet<tblDialyTask> tblDialyTasks { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblVendor_Transaction_Detail> tblVendor_Transaction_Detail { get; set; }
    
        public virtual ObjectResult<sp_get_Customer_Balanace_Result> sp_get_Customer_Balanace()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_Customer_Balanace_Result>("sp_get_Customer_Balanace");
        }
    
        public virtual ObjectResult<sp_view_fee_collection_Result> sp_view_fee_collection(Nullable<System.DateTime> var1, Nullable<int> var2)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(System.DateTime));
    
            var var2Parameter = var2.HasValue ?
                new ObjectParameter("var2", var2) :
                new ObjectParameter("var2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_fee_collection_Result>("sp_view_fee_collection", var1Parameter, var2Parameter);
        }
    
        public virtual int Acc_Update_Journal_Status_Rev_Expense_by_Date(string var1, Nullable<System.DateTime> var2, Nullable<int> var3)
        {
            var var1Parameter = var1 != null ?
                new ObjectParameter("Var1", var1) :
                new ObjectParameter("Var1", typeof(string));
    
            var var2Parameter = var2.HasValue ?
                new ObjectParameter("Var2", var2) :
                new ObjectParameter("Var2", typeof(System.DateTime));
    
            var var3Parameter = var3.HasValue ?
                new ObjectParameter("Var3", var3) :
                new ObjectParameter("Var3", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Acc_Update_Journal_Status_Rev_Expense_by_Date", var1Parameter, var2Parameter, var3Parameter);
        }
    
        public virtual int Add_Journal_Details(Nullable<int> var1, Nullable<int> var2, Nullable<float> var3, Nullable<float> var4)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("Var1", var1) :
                new ObjectParameter("Var1", typeof(int));
    
            var var2Parameter = var2.HasValue ?
                new ObjectParameter("Var2", var2) :
                new ObjectParameter("Var2", typeof(int));
    
            var var3Parameter = var3.HasValue ?
                new ObjectParameter("Var3", var3) :
                new ObjectParameter("Var3", typeof(float));
    
            var var4Parameter = var4.HasValue ?
                new ObjectParameter("Var4", var4) :
                new ObjectParameter("Var4", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Journal_Details", var1Parameter, var2Parameter, var3Parameter, var4Parameter);
        }
    
        public virtual ObjectResult<Nullable<double>> Get_Journal_Balance_By_Account(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("Var1", var1) :
                new ObjectParameter("Var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("Get_Journal_Balance_By_Account", var1Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Get_Max_Journal_id_by_User(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("Var1", var1) :
                new ObjectParameter("Var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Get_Max_Journal_id_by_User", var1Parameter);
        }
    
        public virtual int Sp_Add_Journal(Nullable<System.DateTime> vAR1, Nullable<int> vAR2, Nullable<int> vAR3, string vAR4, string vAR5, Nullable<int> vAR6, string vAR7, string vAR8, string vAR9)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(System.DateTime));
    
            var vAR2Parameter = vAR2.HasValue ?
                new ObjectParameter("VAR2", vAR2) :
                new ObjectParameter("VAR2", typeof(int));
    
            var vAR3Parameter = vAR3.HasValue ?
                new ObjectParameter("VAR3", vAR3) :
                new ObjectParameter("VAR3", typeof(int));
    
            var vAR4Parameter = vAR4 != null ?
                new ObjectParameter("VAR4", vAR4) :
                new ObjectParameter("VAR4", typeof(string));
    
            var vAR5Parameter = vAR5 != null ?
                new ObjectParameter("VAR5", vAR5) :
                new ObjectParameter("VAR5", typeof(string));
    
            var vAR6Parameter = vAR6.HasValue ?
                new ObjectParameter("VAR6", vAR6) :
                new ObjectParameter("VAR6", typeof(int));
    
            var vAR7Parameter = vAR7 != null ?
                new ObjectParameter("VAR7", vAR7) :
                new ObjectParameter("VAR7", typeof(string));
    
            var vAR8Parameter = vAR8 != null ?
                new ObjectParameter("VAR8", vAR8) :
                new ObjectParameter("VAR8", typeof(string));
    
            var vAR9Parameter = vAR9 != null ?
                new ObjectParameter("VAR9", vAR9) :
                new ObjectParameter("VAR9", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Add_Journal", vAR1Parameter, vAR2Parameter, vAR3Parameter, vAR4Parameter, vAR5Parameter, vAR6Parameter, vAR7Parameter, vAR8Parameter, vAR9Parameter);
        }
    
        public virtual int Sp_Add_Journal_Details(Nullable<int> vAR1, Nullable<int> vAR2, Nullable<float> vAR3, Nullable<float> vAR4)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(int));
    
            var vAR2Parameter = vAR2.HasValue ?
                new ObjectParameter("VAR2", vAR2) :
                new ObjectParameter("VAR2", typeof(int));
    
            var vAR3Parameter = vAR3.HasValue ?
                new ObjectParameter("VAR3", vAR3) :
                new ObjectParameter("VAR3", typeof(float));
    
            var vAR4Parameter = vAR4.HasValue ?
                new ObjectParameter("VAR4", vAR4) :
                new ObjectParameter("VAR4", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Add_Journal_Details", vAR1Parameter, vAR2Parameter, vAR3Parameter, vAR4Parameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int Sp_Delete_Cash_Flow_by_Journal_id(Nullable<int> vAR1)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_Cash_Flow_by_Journal_id", vAR1Parameter);
        }
    
        public virtual int Sp_Delete_Journal_by_Tran_Nbr(string vAR1)
        {
            var vAR1Parameter = vAR1 != null ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_Journal_by_Tran_Nbr", vAR1Parameter);
        }
    
        public virtual int Sp_Delete_Journal_Detail_by_ID(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("Var1", var1) :
                new ObjectParameter("Var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_Journal_Detail_by_ID", var1Parameter);
        }
    
        public virtual int Sp_Delete_Journal_Details_by_ID(Nullable<int> vAR1)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_Journal_Details_by_ID", vAR1Parameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Get_Max_Journal_Detail_by_UserID(Nullable<int> vAR1)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Get_Max_Journal_Detail_by_UserID", vAR1Parameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Add_Payment_Voucher(Nullable<System.DateTime> vAR1, Nullable<float> vAR2, string vAR3, string vAR4, Nullable<int> vAR5, Nullable<int> vAR6, string vAR7, string vAR8)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(System.DateTime));
    
            var vAR2Parameter = vAR2.HasValue ?
                new ObjectParameter("VAR2", vAR2) :
                new ObjectParameter("VAR2", typeof(float));
    
            var vAR3Parameter = vAR3 != null ?
                new ObjectParameter("VAR3", vAR3) :
                new ObjectParameter("VAR3", typeof(string));
    
            var vAR4Parameter = vAR4 != null ?
                new ObjectParameter("VAR4", vAR4) :
                new ObjectParameter("VAR4", typeof(string));
    
            var vAR5Parameter = vAR5.HasValue ?
                new ObjectParameter("VAR5", vAR5) :
                new ObjectParameter("VAR5", typeof(int));
    
            var vAR6Parameter = vAR6.HasValue ?
                new ObjectParameter("VAR6", vAR6) :
                new ObjectParameter("VAR6", typeof(int));
    
            var vAR7Parameter = vAR7 != null ?
                new ObjectParameter("VAR7", vAR7) :
                new ObjectParameter("VAR7", typeof(string));
    
            var vAR8Parameter = vAR8 != null ?
                new ObjectParameter("VAR8", vAR8) :
                new ObjectParameter("VAR8", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Payment_Voucher", vAR1Parameter, vAR2Parameter, vAR3Parameter, vAR4Parameter, vAR5Parameter, vAR6Parameter, vAR7Parameter, vAR8Parameter);
        }
    
        public virtual int AddCashFlow(string vAR1, string vAR2, Nullable<int> vAR3, string vAR4, Nullable<float> vAR5, Nullable<float> vAR6)
        {
            var vAR1Parameter = vAR1 != null ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(string));
    
            var vAR2Parameter = vAR2 != null ?
                new ObjectParameter("VAR2", vAR2) :
                new ObjectParameter("VAR2", typeof(string));
    
            var vAR3Parameter = vAR3.HasValue ?
                new ObjectParameter("VAR3", vAR3) :
                new ObjectParameter("VAR3", typeof(int));
    
            var vAR4Parameter = vAR4 != null ?
                new ObjectParameter("VAR4", vAR4) :
                new ObjectParameter("VAR4", typeof(string));
    
            var vAR5Parameter = vAR5.HasValue ?
                new ObjectParameter("VAR5", vAR5) :
                new ObjectParameter("VAR5", typeof(float));
    
            var vAR6Parameter = vAR6.HasValue ?
                new ObjectParameter("VAR6", vAR6) :
                new ObjectParameter("VAR6", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddCashFlow", vAR1Parameter, vAR2Parameter, vAR3Parameter, vAR4Parameter, vAR5Parameter, vAR6Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Get_Max_VoucherID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Get_Max_VoucherID");
        }
    
        public virtual int Add_Vendor_Transaction(Nullable<System.DateTime> vAR1, Nullable<float> vAR2, string vAR3, Nullable<int> vAR4, Nullable<int> vAR5)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(System.DateTime));
    
            var vAR2Parameter = vAR2.HasValue ?
                new ObjectParameter("VAR2", vAR2) :
                new ObjectParameter("VAR2", typeof(float));
    
            var vAR3Parameter = vAR3 != null ?
                new ObjectParameter("VAR3", vAR3) :
                new ObjectParameter("VAR3", typeof(string));
    
            var vAR4Parameter = vAR4.HasValue ?
                new ObjectParameter("VAR4", vAR4) :
                new ObjectParameter("VAR4", typeof(int));
    
            var vAR5Parameter = vAR5.HasValue ?
                new ObjectParameter("VAR5", vAR5) :
                new ObjectParameter("VAR5", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Vendor_Transaction", vAR1Parameter, vAR2Parameter, vAR3Parameter, vAR4Parameter, vAR5Parameter);
        }
    
        public virtual int Add_Vendor_Transaction_Detail(Nullable<int> vAR1, Nullable<float> vAR2, Nullable<float> vAR3, string vAR4, Nullable<int> vAR5, Nullable<System.DateTime> vAR6, Nullable<int> vAR7, string vAR8, string vAR9)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(int));
    
            var vAR2Parameter = vAR2.HasValue ?
                new ObjectParameter("VAR2", vAR2) :
                new ObjectParameter("VAR2", typeof(float));
    
            var vAR3Parameter = vAR3.HasValue ?
                new ObjectParameter("VAR3", vAR3) :
                new ObjectParameter("VAR3", typeof(float));
    
            var vAR4Parameter = vAR4 != null ?
                new ObjectParameter("VAR4", vAR4) :
                new ObjectParameter("VAR4", typeof(string));
    
            var vAR5Parameter = vAR5.HasValue ?
                new ObjectParameter("VAR5", vAR5) :
                new ObjectParameter("VAR5", typeof(int));
    
            var vAR6Parameter = vAR6.HasValue ?
                new ObjectParameter("VAR6", vAR6) :
                new ObjectParameter("VAR6", typeof(System.DateTime));
    
            var vAR7Parameter = vAR7.HasValue ?
                new ObjectParameter("VAR7", vAR7) :
                new ObjectParameter("VAR7", typeof(int));
    
            var vAR8Parameter = vAR8 != null ?
                new ObjectParameter("VAR8", vAR8) :
                new ObjectParameter("VAR8", typeof(string));
    
            var vAR9Parameter = vAR9 != null ?
                new ObjectParameter("VAR9", vAR9) :
                new ObjectParameter("VAR9", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Vendor_Transaction_Detail", vAR1Parameter, vAR2Parameter, vAR3Parameter, vAR4Parameter, vAR5Parameter, vAR6Parameter, vAR7Parameter, vAR8Parameter, vAR9Parameter);
        }
    
        public virtual ObjectResult<Nullable<double>> Get_Total_Vendor_Tranaction_Detial_by_Vendor_TranID(Nullable<int> vAR1)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("Get_Total_Vendor_Tranaction_Detial_by_Vendor_TranID", vAR1Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Get_Vendor_Tran_Type_By_Tran_Type(string vAR1)
        {
            var vAR1Parameter = vAR1 != null ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Get_Vendor_Tran_Type_By_Tran_Type", vAR1Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Get_Vendor_TransactionID_By_Status_VendorID(string vAR1, Nullable<int> vAR2)
        {
            var vAR1Parameter = vAR1 != null ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(string));
    
            var vAR2Parameter = vAR2.HasValue ?
                new ObjectParameter("VAR2", vAR2) :
                new ObjectParameter("VAR2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Get_Vendor_TransactionID_By_Status_VendorID", vAR1Parameter, vAR2Parameter);
        }
    
        public virtual int Update_Vendor_Transaction_Amount_By_Vendor_transid(Nullable<float> vAR1, Nullable<int> vAR2)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(float));
    
            var vAR2Parameter = vAR2.HasValue ?
                new ObjectParameter("VAR2", vAR2) :
                new ObjectParameter("VAR2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Vendor_Transaction_Amount_By_Vendor_transid", vAR1Parameter, vAR2Parameter);
        }
    
        public virtual ObjectResult<Sp_Get_List_of_Cash_Bank_Result> Sp_Get_List_of_Cash_Bank()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_List_of_Cash_Bank_Result>("Sp_Get_List_of_Cash_Bank");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Get_Max_Journal_id_by_User(Nullable<int> vAR1)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Get_Max_Journal_id_by_User", vAR1Parameter);
        }
    
        public virtual int Sp_Update_Vendor_Trans_Total(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_Vendor_Trans_Total", var1Parameter);
        }
    
        public virtual ObjectResult<GetCompanyInfo_Result> GetCompanyInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCompanyInfo_Result>("GetCompanyInfo");
        }
    
        public virtual ObjectResult<sp_Get_Purchase_request_letter_by_ID_Result> sp_Get_Purchase_request_letter_by_ID(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_Purchase_request_letter_by_ID_Result>("sp_Get_Purchase_request_letter_by_ID", var1Parameter);
        }
    
        public virtual ObjectResult<Sp_Get_Cash_Flow_Details_by_Date_Result> Sp_Get_Cash_Flow_Details_by_Date(Nullable<System.DateTime> vAR1, Nullable<System.DateTime> vAR2, Nullable<int> var3)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(System.DateTime));
    
            var vAR2Parameter = vAR2.HasValue ?
                new ObjectParameter("VAR2", vAR2) :
                new ObjectParameter("VAR2", typeof(System.DateTime));
    
            var var3Parameter = var3.HasValue ?
                new ObjectParameter("var3", var3) :
                new ObjectParameter("var3", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Cash_Flow_Details_by_Date_Result>("Sp_Get_Cash_Flow_Details_by_Date", vAR1Parameter, vAR2Parameter, var3Parameter);
        }
    
        public virtual ObjectResult<sp_get_qty_available_by_division_date_Details_Result> sp_get_qty_available_by_division_date_Details(Nullable<int> var1, Nullable<System.DateTime> var2)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            var var2Parameter = var2.HasValue ?
                new ObjectParameter("var2", var2) :
                new ObjectParameter("var2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_qty_available_by_division_date_Details_Result>("sp_get_qty_available_by_division_date_Details", var1Parameter, var2Parameter);
        }
    
        public virtual ObjectResult<sp_get_qty_available_by_division_date_Result> sp_get_qty_available_by_division_date(Nullable<int> var1, Nullable<System.DateTime> var2)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            var var2Parameter = var2.HasValue ?
                new ObjectParameter("var2", var2) :
                new ObjectParameter("var2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_qty_available_by_division_date_Result>("sp_get_qty_available_by_division_date", var1Parameter, var2Parameter);
        }
    
        public virtual ObjectResult<sp_Get_Purchase_Receipt_by_ID_Result> sp_Get_Purchase_Receipt_by_ID(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_Purchase_Receipt_by_ID_Result>("sp_Get_Purchase_Receipt_by_ID", var1Parameter);
        }
    
        public virtual ObjectResult<Nullable<double>> Inv_Get_Qty_Available_by_ProductID(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("Var1", var1) :
                new ObjectParameter("Var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("Inv_Get_Qty_Available_by_ProductID", var1Parameter);
        }
    
        public virtual ObjectResult<Nullable<double>> Get_Total_Customer_Transaction_Detail_by_TranID(Nullable<int> vAR1)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("Get_Total_Customer_Transaction_Detail_by_TranID", vAR1Parameter);
        }
    
        public virtual int Update_Customer_Tranaction_Amount_By_Cust_tran_id(Nullable<float> vAR1, Nullable<int> vAR2)
        {
            var vAR1Parameter = vAR1.HasValue ?
                new ObjectParameter("VAR1", vAR1) :
                new ObjectParameter("VAR1", typeof(float));
    
            var vAR2Parameter = vAR2.HasValue ?
                new ObjectParameter("VAR2", vAR2) :
                new ObjectParameter("VAR2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Customer_Tranaction_Amount_By_Cust_tran_id", vAR1Parameter, vAR2Parameter);
        }
    
        public virtual ObjectResult<Sp_Get_Cash_Bank_Account_Result> Sp_Get_Cash_Bank_Account()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Cash_Bank_Account_Result>("Sp_Get_Cash_Bank_Account");
        }
    
        public virtual ObjectResult<sp_Get_Customer_with_Balance_Result> sp_Get_Customer_with_Balance(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_Customer_with_Balance_Result>("sp_Get_Customer_with_Balance", var1Parameter);
        }
    
        public virtual ObjectResult<Pro_Get_Invoice_Group_Details_Result> Pro_Get_Invoice_Group_Details(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_Get_Invoice_Group_Details_Result>("Pro_Get_Invoice_Group_Details", var1Parameter);
        }
    
        public virtual ObjectResult<sp_get_customer_transactions_by_id_Result> sp_get_customer_transactions_by_id(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_customer_transactions_by_id_Result>("sp_get_customer_transactions_by_id", var1Parameter);
        }
    
        public virtual ObjectResult<Nullable<double>> sp_check_item_batch(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_check_item_batch", var1Parameter);
        }
    
        public virtual ObjectResult<sp_get_items_with_batch_qty_Result> sp_get_items_with_batch_qty(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_items_with_batch_qty_Result>("sp_get_items_with_batch_qty", var1Parameter);
        }
    
        public virtual ObjectResult<sp_get_qty_available_by_division_Result> sp_get_qty_available_by_division(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_qty_available_by_division_Result>("sp_get_qty_available_by_division", var1Parameter);
        }
    
        public virtual ObjectResult<sp_Get_Sales_Receipt_by_ID_Result> sp_Get_Sales_Receipt_by_ID(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_Sales_Receipt_by_ID_Result>("sp_Get_Sales_Receipt_by_ID", var1Parameter);
        }
    
        public virtual int Sp_Update_Customer_Trans_Total(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Update_Customer_Trans_Total", var1Parameter);
        }
    
        public virtual ObjectResult<View_Item_Sales_Result> View_Item_Sales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_Item_Sales_Result>("View_Item_Sales");
        }
    
        public virtual ObjectResult<Search_Customer_By_Name_Result> Search_Customer_By_Name(string var1)
        {
            var var1Parameter = var1 != null ?
                new ObjectParameter("Var1", var1) :
                new ObjectParameter("Var1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Customer_By_Name_Result>("Search_Customer_By_Name", var1Parameter);
        }
    
        public virtual ObjectResult<pro_Get_Invoice_Result> pro_Get_Invoice(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_Get_Invoice_Result>("pro_Get_Invoice", var1Parameter);
        }
    
        public virtual ObjectResult<sp_Get_Customer_with_Balance2_Result> sp_Get_Customer_with_Balance2(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Get_Customer_with_Balance2_Result>("sp_Get_Customer_with_Balance2", var1Parameter);
        }
    
        public virtual ObjectResult<Pro_Tasks_List_Result> Pro_Tasks_List(string var1)
        {
            var var1Parameter = var1 != null ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_Tasks_List_Result>("Pro_Tasks_List", var1Parameter);
        }
    
        public virtual int sp_resset()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_resset");
        }
    
        public virtual ObjectResult<pro_Get_Invoice_By_Group_Result> pro_Get_Invoice_By_Group(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_Get_Invoice_By_Group_Result>("pro_Get_Invoice_By_Group", var1Parameter);
        }
    
        public virtual ObjectResult<View_All_Customers_Result> View_All_Customers(string var1, string var2, string var3)
        {
            var var1Parameter = var1 != null ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(string));
    
            var var2Parameter = var2 != null ?
                new ObjectParameter("var2", var2) :
                new ObjectParameter("var2", typeof(string));
    
            var var3Parameter = var3 != null ?
                new ObjectParameter("var3", var3) :
                new ObjectParameter("var3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_All_Customers_Result>("View_All_Customers", var1Parameter, var2Parameter, var3Parameter);
        }
    
        public virtual ObjectResult<View_All_Customers_By_Name_Type_Status_Result> View_All_Customers_By_Name_Type_Status(string var1, string var2, string var3)
        {
            var var1Parameter = var1 != null ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(string));
    
            var var2Parameter = var2 != null ?
                new ObjectParameter("var2", var2) :
                new ObjectParameter("var2", typeof(string));
    
            var var3Parameter = var3 != null ?
                new ObjectParameter("var3", var3) :
                new ObjectParameter("var3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_All_Customers_By_Name_Type_Status_Result>("View_All_Customers_By_Name_Type_Status", var1Parameter, var2Parameter, var3Parameter);
        }
    
        public virtual ObjectResult<View_Customer_Maintainance_Result> View_Customer_Maintainance(Nullable<int> var1, Nullable<int> var2)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            var var2Parameter = var2.HasValue ?
                new ObjectParameter("var2", var2) :
                new ObjectParameter("var2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<View_Customer_Maintainance_Result>("View_Customer_Maintainance", var1Parameter, var2Parameter);
        }
    
        public virtual ObjectResult<sp_get_customer_transactions_by_id_Date_Tran_Type_Result> sp_get_customer_transactions_by_id_Date_Tran_Type(Nullable<int> var1, Nullable<int> var2, Nullable<System.DateTime> var3, Nullable<System.DateTime> var4)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            var var2Parameter = var2.HasValue ?
                new ObjectParameter("var2", var2) :
                new ObjectParameter("var2", typeof(int));
    
            var var3Parameter = var3.HasValue ?
                new ObjectParameter("var3", var3) :
                new ObjectParameter("var3", typeof(System.DateTime));
    
            var var4Parameter = var4.HasValue ?
                new ObjectParameter("var4", var4) :
                new ObjectParameter("var4", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_customer_transactions_by_id_Date_Tran_Type_Result>("sp_get_customer_transactions_by_id_Date_Tran_Type", var1Parameter, var2Parameter, var3Parameter, var4Parameter);
        }
    
        public virtual ObjectResult<sp_get_vendor_transactions_by_id_Result> sp_get_vendor_transactions_by_id(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_vendor_transactions_by_id_Result>("sp_get_vendor_transactions_by_id", var1Parameter);
        }
    
        public virtual ObjectResult<sp_get_vendor_transactions_by_id_Date_Tran_Type_Result> sp_get_vendor_transactions_by_id_Date_Tran_Type(Nullable<int> var1, Nullable<int> var2, Nullable<System.DateTime> var3, Nullable<System.DateTime> var4)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            var var2Parameter = var2.HasValue ?
                new ObjectParameter("var2", var2) :
                new ObjectParameter("var2", typeof(int));
    
            var var3Parameter = var3.HasValue ?
                new ObjectParameter("var3", var3) :
                new ObjectParameter("var3", typeof(System.DateTime));
    
            var var4Parameter = var4.HasValue ?
                new ObjectParameter("var4", var4) :
                new ObjectParameter("var4", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_vendor_transactions_by_id_Date_Tran_Type_Result>("sp_get_vendor_transactions_by_id_Date_Tran_Type", var1Parameter, var2Parameter, var3Parameter, var4Parameter);
        }
    
        public virtual ObjectResult<Sp_Get_Vendor_with_Balance_Result> Sp_Get_Vendor_with_Balance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Vendor_with_Balance_Result>("Sp_Get_Vendor_with_Balance");
        }
    
        public virtual ObjectResult<pro_Get_Vendor_Invoice_Result> pro_Get_Vendor_Invoice(Nullable<int> var1)
        {
            var var1Parameter = var1.HasValue ?
                new ObjectParameter("var1", var1) :
                new ObjectParameter("var1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_Get_Vendor_Invoice_Result>("pro_Get_Vendor_Invoice", var1Parameter);
        }
    }
}
