//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppVersion
    {
        public int App_ID { get; set; }
        public string App_Name { get; set; }
        public Nullable<float> Latest_Version { get; set; }
        public Nullable<System.DateTime> Last_Update_Date { get; set; }
        public string Notes { get; set; }
    }
}
