//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBatch
    {
        public int Batch_id { get; set; }
        public string Batch { get; set; }
        public Nullable<System.DateTime> Manufacture_Date { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
        public Nullable<int> Inventory_Detail_id { get; set; }
    }
}
