//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCash_Flow
    {
        public int Cash_Flow_ID { get; set; }
        public string Tran_Type { get; set; }
        public string Description { get; set; }
        public int Journal_Detail_id { get; set; }
        public string Tran_Nbr { get; set; }
        public Nullable<float> Debit { get; set; }
        public Nullable<float> Credit { get; set; }
    }
}
