//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConnection_Data
    {
        public int Connection_ID { get; set; }
        public string Customer { get; set; }
        public Nullable<int> Generated_by { get; set; }
        public System.DateTime Generated_Date { get; set; }
        public string Pass_Code { get; set; }
        public string Database_Server { get; set; }
        public string Database_User { get; set; }
        public string Database_Password { get; set; }
        public string Database_Name { get; set; }
        public System.DateTime Expire_Date { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
