//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCashFlow
    {
        public int CashFlowID { get; set; }
        public Nullable<System.DateTime> Tran_Date { get; set; }
        public Nullable<float> Debit { get; set; }
        public Nullable<float> Credit { get; set; }
        public string Type { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Description { get; set; }
    }
}
