//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChart_Of_Accounts
    {
        public int Account_Number { get; set; }
        public string Account_Name { get; set; }
        public string Transaction_Type { get; set; }
        public string Account_Main_Group { get; set; }
        public string Account_Sub_Group { get; set; }
        public Nullable<int> Level_SLNO { get; set; }
        public string Cash_Or_Bank { get; set; }
        public string Affect_Gross_Profit { get; set; }
        public Nullable<int> Parent_id { get; set; }
        public Nullable<int> Sort_Rank { get; set; }
        public Nullable<int> Account_Class_Id { get; set; }
        public Nullable<int> DrOrCrSide { get; set; }
        public Nullable<int> level { get; set; }
        public string Sub_Type { get; set; }
        public string Account_Group { get; set; }
    }
}
