//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomer()
        {
            this.tblDialyTasks = new HashSet<tblDialyTask>();
        }
    
        public int CustomerID { get; set; }
        public string Customer_Name { get; set; }
        public string Address { get; set; }
        public string Cutomer_Type { get; set; }
        public string Status { get; set; }
        public string Contact_Numbers { get; set; }
        public Nullable<System.DateTime> Contract_Date { get; set; }
        public Nullable<float> Maintainance { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDialyTask> tblDialyTasks { get; set; }
    }
}
