//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer_Transaction_Detail
    {
        public int Cust_Transaction_Detail_id { get; set; }
        public int Cust_Tran_ID { get; set; }
        public float Debit { get; set; }
        public float Credit { get; set; }
        public Nullable<float> Qty { get; set; }
        public Nullable<float> Unit_price { get; set; }
        public string Description { get; set; }
        public int UserID { get; set; }
        public System.DateTime Trans_Date { get; set; }
        public int Cust_Tran_Type_ID { get; set; }
        public string Status { get; set; }
        public string Tran_Nbr { get; set; }
        public string Route { get; set; }
        public string Airline { get; set; }
        public Nullable<float> Amount { get; set; }
        public Nullable<System.DateTime> Dept_Date { get; set; }
        public Nullable<int> Invoice_Group_Id { get; set; }
        public Nullable<int> Booking_ID { get; set; }
        public Nullable<int> Inventory_Tran_ID { get; set; }
        public Nullable<int> Invoice_No { get; set; }
        public Nullable<float> Balance { get; set; }
    }
}
