//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDocument
    {
        public int Doc_Id { get; set; }
        public string Documents { get; set; }
        public string Cust_Name { get; set; }
        public string RefNo { get; set; }
        public System.DateTime Tran_Date { get; set; }
    }
}
