//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpense
    {
        public int Expense_ID { get; set; }
        public System.DateTime Expense_Date { get; set; }
        public int Expense_Type_ID { get; set; }
        public Nullable<float> Dr { get; set; }
        public float Cr { get; set; }
        public Nullable<float> Balance { get; set; }
        public int UserID { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public string Voucher { get; set; }
        public string Payment_Method { get; set; }
        public int Period { get; set; }
        public int Year { get; set; }
        public int Quarter { get; set; }
        public string Tran_Nbr { get; set; }
    }
}
