//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExpenseType
    {
        public int Expense_Type_ID { get; set; }
        public string Expense_Type { get; set; }
        public int Account_Number { get; set; }
        public string Is_Cogs_Item { get; set; }
    }
}
