//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeatureRequest
    {
        public int Feature_ID { get; set; }
        public Nullable<int> Application_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Importance { get; set; }
        public Nullable<System.DateTime> Requested_date { get; set; }
        public string Status { get; set; }
    }
}
