//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventory_Transactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInventory_Transactions()
        {
            this.tblInventory_Transaction_Details = new HashSet<tblInventory_Transaction_Details>();
        }
    
        public int Inventory_Tran_ID { get; set; }
        public System.DateTime Tran_Date { get; set; }
        public int Inventory_type_id { get; set; }
        public string Payment_Method { get; set; }
        public string Tran_Nbr { get; set; }
        public float Total { get; set; }
        public string Status { get; set; }
        public int UserID { get; set; }
        public int Business_Division_Id { get; set; }
        public string Payment_Status { get; set; }
        public float Discount { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Vendor_ID { get; set; }
        public Nullable<int> Marketer_id { get; set; }
        public Nullable<int> Invoice_No { get; set; }
        public Nullable<float> Cash_Payment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventory_Transaction_Details> tblInventory_Transaction_Details { get; set; }
        public virtual Business_Division Business_Division { get; set; }
    }
}
