//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceGroupDetail
    {
        public Nullable<int> Invoice_Group_Id { get; set; }
        public Nullable<int> Cust_Transaction_Detail_id { get; set; }
        public int ID { get; set; }
        public Nullable<float> QTY { get; set; }
    }
}
