//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventory_Transaction_Details
    {
        public int Inventory_Tran_Detail_ID { get; set; }
        public int Inventory_Tran_ID { get; set; }
        public int Item_Id { get; set; }
        public float Unit_Price { get; set; }
        public float Qty_In { get; set; }
        public float Qty_Out { get; set; }
        public float Sales_price { get; set; }
        public string Batch { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Freight { get; set; }
        public string Barcode { get; set; }
    
        public virtual tblInventory_Transactions tblInventory_Transactions { get; set; }
    }
}
