//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJournal
    {
        public int Journal_id { get; set; }
        public System.DateTime Journal_Date { get; set; }
        public int Period { get; set; }
        public int TYear { get; set; }
        public string Tran_Nbr { get; set; }
        public string Description { get; set; }
        public int UserID { get; set; }
        public string Status { get; set; }
        public string Tran_Type { get; set; }
        public string Journal_Type { get; set; }
    }
}
