//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJournal_Details
    {
        public int Journal_Detail_id { get; set; }
        public int Journal_id { get; set; }
        public int Account_Number { get; set; }
        public Nullable<float> Debit { get; set; }
        public Nullable<float> Credit { get; set; }
        public string Status { get; set; }
    }
}
