//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProblem
    {
        public int Problem_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Status { get; set; }
        public string Solution_Note { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
        public Nullable<int> Application_ID { get; set; }
        public string User { get; set; }
        public string Type { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> SolvedDate { get; set; }
    
        public virtual tblApplication tblApplication { get; set; }
    }
}
