//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        public int Project_ID { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Application { get; set; }
        public Nullable<float> Total_Cost { get; set; }
        public string Status { get; set; }
        public string Quotation_Link { get; set; }
        public string PaymentAgreement_Link { get; set; }
        public string Priority { get; set; }
        public Nullable<int> Created_by { get; set; }
        public Nullable<float> Payments { get; set; }
        public string Agreement_Status { get; set; }
        public string Project_Title { get; set; }
    }
}
