//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReceipt_Voucher
    {
        public int Voucher_ID { get; set; }
        public System.DateTime Receipt_Date { get; set; }
        public float Amount { get; set; }
        public string Payee { get; set; }
        public string In_Word { get; set; }
        public int UserID { get; set; }
        public int Company_ID { get; set; }
        public string Description { get; set; }
        public string Tran_Nbr { get; set; }
        public Nullable<float> Balance { get; set; }
    }
}
