//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSMS_API_DATA
    {
        public int SMS_SENT_ID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Short_Name { get; set; }
        public string Phone { get; set; }
        public string SMS_Body { get; set; }
        public string Request_Url { get; set; }
    }
}
