//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        public int Vendor_ID { get; set; }
        public string Vendor_Name { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
    }
}
