//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor_Documents
    {
        public int ID { get; set; }
        public Nullable<int> Vendor_ID { get; set; }
        public string Document_Description { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> Document_Date { get; set; }
    }
}
