//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SameSoftWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWebLog
    {
        public int ID { get; set; }
        public System.DateTime Log_Date { get; set; }
        public string Type { get; set; }
        public string Details { get; set; }
    }
}
